name: iOSGithubCI
options:
  bundleIdPrefix: com.iosgithubci
settings:
  base:
    DEVELOPMENT_TEAM: F6395XL53N

targets:
  App:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources: [App]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.iosgithubci.iOSGithubCI
        PROVISIONING_PROFILE_SPECIFIER: "iOSGithubCI"
        APP_DISPLAY_NAME: iOSGithubCI
        PRODUCT_NAME: iOSGithubCI
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "iPhone Distribution"
    scheme:
      testTargets: [App_Tests]
    info:
      path: App/Info.plist
      properties:
        CFBundleDisplayName: $(APP_DISPLAY_NAME)
        CFBundleShortVersionString: "1.0"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UILaunchScreen:
          UIRequiredDeviceCapabilities: [armv7]
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
  App_Tests:
    type: bundle.unit-test
    platform: iOS
    sources: [App_Tests]
