name: iOSGithubCI
options:
  bundleIdPrefix: com.iosgithubci
  deploymentTarget: "14.0"
settings:
  base:
    DEVELOPMENT_TEAM: F6395XL53N
    DISABLE_DIAMOND_PROBLEM_DIAGNOSTIC: 1
targets:
  App:
    type: application
    platform: iOS
    sources: [App]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.iosgithubci.iOSGithubCI
        PROVISIONING_PROFILE_SPECIFIER: "iOSGithubCI"
        APP_DISPLAY_NAME: iOSGithubCI
        PRODUCT_NAME: iOSGithubCI
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "iPhone Distribution"
    scheme:
      testTargets: [App_Tests]
    info:
      path: App/Info.plist
      properties:
        CFBundleDisplayName: $(APP_DISPLAY_NAME)
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "3"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UILaunchScreen:
          UIRequiredDeviceCapabilities: [armv7]
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    dependencies:
      - target: HelloWorld
      - target: Add

  App_Tests:
    type: bundle.unit-test
    platform: iOS
    sources: [App_Tests]

  HelloWorld:
    type: framework
    platform: iOS
    sources: [HelloWorld]
    dependencies:
      - package: Prelude
        product: Prelude
        product: Optics
    info:
      path: HelloWorld/Info.plist

  Add:
    type: framework
    platform: iOS
    sources: [Add]
    dependencies:
      - package: Prelude
        product: Prelude
        product: Optics
    info:
      path: HelloWorld/Info.plist

packages:
  Prelude:
    url: https://github.com/pointfreeco/swift-prelude.git
    branch: master

