name: Deploy
on:
  pull_request:
    branches:
    - master
jobs:
  deploy:
    name: Deploying to AppStore
    runs-on: macOS-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: XcodeGen
        uses: xavierLowmiller/xcodegen-action@1.1.1
        with:
          version: 2.18.0
      - name: Use Xcode 12.3
        run: sudo xcode-select -switch /Applications/Xcode_12.3.app
      - name: Install gpg
        run: brew install gnupg
      - name: Setup Credentials
        run: make init-deployment-secrets
        env:
          DECRYPT_KEY: ${{ secrets.DECRYPT_KEY }}
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
      - name: Archive and Export
        run: make archive
      - name: Upload to TestFlight
        run: |
          APPLEID_USERNAME=${{ secrets.APPLEID_USERNAME }} \
          APPLEID_PASSWORD=${{ secrets.APPLEID_PASSWORD }} \
          make upload
