name: PR-Testing
on:
  pull_request:
    branches:
    - master
jobs:
  test:
    name: Testing iOS app
    runs-on: macOS-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: XcodeGen
        uses: xavierLowmiller/xcodegen-action@1.1.1
        with:
          version: 2.18.0

      - name: Cache SPM
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-


      - name: Use Xcode 12.3
        run: sudo xcode-select -switch /Applications/Xcode_12.3.app

      - name: Test iOS app
        run: time make test
