name: PR-Testing
on:
  pull_request:
    branches:
    - master
jobs:
  test:
    name: Testing iOS app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: XcodeGen
        uses: xavierLowmiller/xcodegen-action@1.0.0
        with:
          version: '2.18.0'
      - name: Force Xcode 12.3
        run: sudo xcode-select -switch /Applications/Xcode_12.3.app
      - name: Testing iOS app
        run: time make test
